config/routes.rb
Rails.application.routes.draw do

 resources :doses, only: [ :destroy, :show ]

  resources :cocktails do
   resources :doses, only: [ :index, :new, :create ]
 end

 root 'cocktails#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :ingredient, :scope => :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :do_more_magic, only: [:show, :edit, :update, :destroy]

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @ingredient = Ingredient.new
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
     else
      render :new
    end
  end

  def show
    # @ingredients = Ingredient.where(id: Dose.where(cocktail_id: @cocktail))
    @doses = @cocktail.doses


    @doses = Dose.where(cocktail_id: @cocktail)
    @ingredient = Ingredient.new
  end

  def index
    @cocktails = Cocktail.all
  end

  def destroy
  end

  def edit
  end

  def update
  end

  private

  def do_more_magic
    @cocktail = Cocktail.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
 def new
  @dose = Dose.new
  @cocktail = Cocktail.find(params[:cocktail_id])
 end

def create
  @ingredient = Ingredient.new
  @dose = Dose.new(dose_params)
  @cocktail = Cocktail.find(params[:cocktail_id])
  @dose.cocktail = @cocktail

  if @dose.save
    redirect_to cocktail_path(params[:cocktail_id])
  else
    render :new
  end
end

def show
end

def index
  @doses = Dose.all
end

private

  # Never trust parameters from the scary internet, only allow the white list through.
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="row">
<%= simple_form_for(@cocktail) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit :class => 'btn btn-primary' %>

<% end %>
</div>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<div class="text-center">
<h1>Cocktails#index</h1>
   <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i>'.html_safe, new_cocktail_path %>
   <br>

  <% @cocktails.each do |cocktail| %>
  <h1><%= link_to cocktail.name, cocktail_path(cocktail)  %></h1>
  <%= link_to '<i class="fa fa-add" aria-hidden="true"></i>'.html_safe, edit_cocktail_path(cocktail) %>

  <% end %>

  <%= cl_image_tag("loool", width: 400, height: 300, crop: :fill) %>
</div>

app/views/cocktails/new.html.erb
<div class="text-center">
  <h1>Cocktails#new</h1>

  <%= render 'form' %>

  <% GoogleCustomSearchApi.search("mojito", searchType: "image" ).items.each do |item| %>
   <%= image_tag item.link %>
    <% end  %>


<%= link_to "google", "link_to lool, 'www.google.com' " %>
  </div>

app/views/cocktails/show.html.erb
<div class="text-center">
  <h1>Cocktails#show</h1>

  <h1><%= @cocktail.name %></h1>

  <br>
  <br>

  <h1>Ingredients</h1>
  <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i>'.html_safe, new_cocktail_dose_path(@cocktail) %>

  <% @doses.each do |dose| %>
  <div class="panel panel-default">
    <h4><%= dose.ingredient.name %></h4>
    <p><%= dose.description %></p>
  </div>
  <% end %>

  <p><%= link_to "Back", cocktails_path  %></p>
</div>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/_form.html.erb
<div class="row">
<%= simple_form_for [@cocktail, @dose] do |f| %>

  <%= f.input :description %>

  <%= f.input :ingredient_id, collection: Ingredient.all%>

  <%= f.submit :class => 'btn btn-primary' %>

  <% end %>
</div>

<!--
simple_form_for @dose(nil)

dose_path (create method)

simple_form_for @dose(data)

dose_path(patch)

simple_form_for @cocktail, @dose(nil)

new_cocktail_dose_path

simple_form_for @cocktail, @dose(data)

update_cocktail_dose_path -->

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<div class="text-center">
  <h1>Doses#new</h1>

  <%= render 'form' %>

</div>

app/views/doses/show.html.erb
kladjlkasl

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>